export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_LOCATION = 'CLEAR_LOCATION';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GET_LOCATION = 'GET_LOCATION';
export const GET_LATLNG = 'GET_LATLNG';
export const ADD_LOCATION = 'ADD_LOCATION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';
export const LOCATION_ERROR = 'LOCATION_ERROR';

export const GET_WEATHERS = 'GET_WEATHERS';
export const GET_WEATHER = 'GET_WEATHER';
export const REMOVE_WEATHER = 'REMOVE_WEATHER';
export const CLEAR_WEATHER = 'CLEAR_WEATHER';
export const WEATHER_ERROR = 'WEATHER_ERROR';
